### ISSUE TITLE
messages->orderActivated,显示重复

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#104] opened 2017-12-15 06:57 UTC
1. 一个order选择2个pilots，生成2个order，message list里有4条信息，每个pilot两条信息，且时间相同
2. 点开任何一个OrderActivated，没有关于订单编号的提示，
3.pilot难以区分那个operator对应哪个order
![282323715253084390](https://user-images.githubusercontent.com/33741789/34030481-3a49525c-e1a8-11e7-84e1-f5ffc76e0879.jpg)
![483296259974105042](https://user-images.githubusercontent.com/33741789/34030484-3d102f1a-e1a8-11e7-846c-cecaeac5e049.jpg)

**Comment by tianjilanfeng** [comment] 2017-12-16 14:29
Assign to bruno only

**Comment by Mobiusor** [comment] 2017-12-24 05:22
no order id is by design, disable button when click confirm button so no duplicated orders will be made,

**Closed as completed** 2017-12-25 21:53 UTC
Labels: mid priority, Operator App
