### ISSUE TITLE
Registration country is short listed

### ISSUE THREAD

**Issue by Jean2099** [Mobiusor/aerolink-issue#122] opened 2017-12-25 09:24 UTC
![473f150e8f7aa697780b3de62b66185](https://user-images.githubusercontent.com/33741789/34337190-6b2929cc-e998-11e7-8b4b-d58e5e921cbc.png)

**Comment by licetus** [comment] 2017-12-26 11:59
by design, won't fix

**Closed as completed** 2017-12-28 08:05 UTC
Labels: operator web
